name: "Setup"

on: 
  workflow_call:

jobs:
  setup:
    strategy:
      matrix:
        os: ['ubuntu-24.04', 'macos-15']
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: 'Checkout code'
      - uses: actions/checkout@v4

      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools