name: "Lint Plugin"

on: 
  workflow_call:

jobs:
  lint:
    runs-on: 'macos-15'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools

      - name: 'Lint Packages'
        working-directory: ./packages/capacitor-plugin
        run: npm run lint